version: '3.8'

services:
  learning-map-app:
    build: .
    ports:
      - "8008:8008"
    environment:
      - POCKETBASE_URL=${POCKETBASE_URL}
      - POCKETBASE_EMAIL=${POCKETBASE_EMAIL}
      - POCKETBASE_PASSWORD=${POCKETBASE_PASSWORD}
      - SECRET=${SECRET}
      - API_BASE=${API_BASE}
      - API_KEY=${API_KEY}
      - MODEL=${MODEL:-llama3.1:8b}
      - CUSTOM_LLM_PROVIDER=${CUSTOM_LLM_PROVIDER}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      # Mount the current directory for development
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
